version: '3.8'

services:
  db:
    image: postgres:17.5-bookworm
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: beAnalytic
      POSTGRES_DB: IDA
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-web
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@docker.com
      PGADMIN_DEFAULT_PASSWORD: beAnalytic
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8080:80"
    depends_on:
      - db

  app:
    build: .
    container_name: python-app
    depends_on:
      - db

volumes:
  db-data:
  pgadmin-data: